# -*- coding: utf-8 -*-
"""Kalkulator Turunan_limit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157Q0OE7Z2jWA-uL307cq2_9te-gyVPZN
"""

!pip install streamlit pyngrok --quiet

import streamlit as st
import sympy as sp

# Judul aplikasi
st.title("🧮 Kalkulator Turunan Pertama Menggunakan Definisi Limit")

# Input dari pengguna
fungsi_input = st.text_input("Masukkan fungsi f(x):", "x**2 + 3*x + 2")
titik = st.number_input("Hitung turunan di titik x =", value=2.0, step=0.1)

# Tombol untuk menghitung
if st.button("Hitung Turunan"):
    x, h = sp.symbols('x h')  # definisikan simbol

    try:
        # Ubah string menjadi ekspresi matematika
        fungsi = sp.sympify(fungsi_input)

        # Hitung turunan pertama menggunakan limit
        turunan_limit = sp.limit((fungsi.subs(x, x + h) - fungsi) / h, h, 0)

        # Evaluasi turunan di titik tertentu
        nilai_turunan = turunan_limit.subs(x, titik)

        # Tampilkan hasil
        st.latex(r"f'(x) = \lim_{h \to 0} \frac{f(x+h) - f(x)}{h}")
        st.latex(f"f(x) = {sp.latex(fungsi)}")
        st.latex(f"f'(x) = {sp.latex(turunan_limit)}")
        st.success(f"f'({titik}) = {nilai_turunan}")

    except Exception as e:
        st.error(f"Terjadi kesalahan saat memproses fungsi: {e}")